spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: authorization-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://122.9.7.252:3306/cloud_music_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: grf.2001
        sharding: # 从这里指定 sharding
          url: jdbc:shardingsphere:classpath:sharding-sphere-config.yaml
          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver




mybatis:
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true

jwt:
  signing-key: oJJB72CmVtKFf5h8i63xYHzPcob96L12
  # 为了测试，这里将 AccessToken 的过期时间设置为 30 Day
  # 正常设置为 10 分钟即可，即 600
  expireTimeOfAccessToken: 2678400
  expireTimeOfRefreshToken: 2678400

oss:
  endpoint: https://oss-cn-qingdao.aliyuncs.com
  access-key:
    id: LTAI5t9Sd2WnZzLo4BPcFjGY
    secret: oJJB72CmVtKFf5h8i63xYHzPcob96L


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: shandong
    availability-zones:
      shandong: linyi
    service-url:
      linyi: http://localhost:30010/eureka/
  instance:
    metadata-map:
      zone: linyi
    hostname: localhost

server:
  port: 30001

tinyid:
  user: test
