spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: music-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: grf.2001
    url: jdbc:mysql://122.9.36.231:3306/cloud_music_song?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
server:
  port: 30003

mybatis:
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: INFO
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO

jwt:
  signing-key: oJJB72CmVtKFf5h8i63xYHzPcob96L12

oss:
  endpoint: https://oss-cn-qingdao.aliyuncs.com
  access-key:
    id: LTAI5t9Sd2WnZzLo4BPcFjGY
    secret: oJJB72CmVtKFf5h8i63xYHzPcob96L

eureka:
  client:
    region: shandong
    availability-zones:
      shandong: linyi
    service-url:
      linyi: http://eureka-server-cluster-ip:30010/eureka/
  instance:
    metadata-map:
      zone: linyi
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
